### ISSUE TITLE
Orchestrate delete policies

### ISSUE THREAD

**Issue by jbonnet** [sonata-nfv/tng-gtk-sp#136]
When a package containing a service is deleted, policies mentioning it should also be deleted.

what should hapen if deleting the package (with the service) succeeds, but deleting policies fails?
could we require the user to first delete policies of a service and then the package containing that same service?
do you delete-delete the policy, or just mark as ‘deleted'? What happens to the records mentioning the policy?

**Comment by efotopoulou** [comment]
maybe we should follow a conservative approach. 
Fist of all a service can not be deleted if it is deployed. in this case the enforced policies are also protected from the deletion action.

if a package containing a service is deleted and a) this service is not deployed yet  b) there is a policy for this network service then the deletion action should be avoided with a friendly message that should inform the applicant that has to delete the relevant policies firstly.

**Comment by jbonnet** [comment]
We're not going to implement this...
