### ISSUE TITLE
Return SLAs associated with each service 

### ISSUE THREAD

**Issue by anapolg** [sonata-nfv/tng-gtk-sp#163]
In the request GET https://int-sp-ath.5gtango.eu/api/v3/services the response should include the SLAs associated to each service. The SLA information needed is:
 { 
      vendor, 
      name, 
      version, 
      uuid 
}

**Comment by jbonnet** [comment]
This will be done only when a specific service (`.../api/v3/services/:uuid`) is requested

**Comment by jbonnet** [comment]
We're not going to implement this...
