### ISSUE TITLE
Status code 500 when deleting a slice template

### ISSUE THREAD

**Issue by tsoenen** [sonata-nfv/tng-gtk-sp#222]
When deleting a slice template using /api/v3/slices/<slice_template_uuid>, the slice template is successfully deleted, but the response status code is 500.

The payload of the response isn't processable as a json object.

@jbonnet @alemanyp

**Comment by jbonnet** [comment]
Possibly solved by PR #226 
@tsoenen can you please test it again?

**Comment by jbonnet** [comment]
Hey @tsoenen @alemanyp can we close this issue?
