### ISSUE TITLE
/api/v3/request is slow

### ISSUE THREAD

**Issue by tsoenen** [sonata-nfv/tng-gtk-sp#224]
I have noticed that GET or POST requests to `/api/v3/request` are taking significantly longer than other `api/v3/...` requests.

Time-outs of 5+ seconds are frequently observed.

**Comment by jbonnet** [comment]
Thanks, @tsoenen 
`GET` requests tries to complement data on the requested service by going to the Catalogue and fetching service name, vendor and version. We've got cacheing here, using a Redis DB. 'POST' saves requests in a PostgreSQL DB, maybe this one needs some love?

**Comment by jbonnet** [comment]
Same as #240: service vendor, name and version will be added to the requests table
