### ISSUE TITLE
Wrong status code when requesting service instantiation with corrupt uuid

### ISSUE THREAD

**Issue by tsoenen** [sonata-nfv/tng-gtk-sp#237]
When requesting the instantiation of a service with a corrupt service uuid, the response from the GK has status code 201 with an empty message.

**Comment by jbonnet** [comment]
Thanks, @tsoenen. Would it be enough to validate the UUID format (dashes plus the number of characters in between) or is it needed that we do a full request to the Catalogue to verify it's existence?

**Comment by tsoenen** [comment]
I would say the second. If the GK receives a request with a uuid that is not a service uuid, the response should state this.

**Comment by jbonnet** [comment]
We're not going to implement this one
