### ISSUE TITLE
instance name not displayed 

### ISSUE THREAD

**Issue by anapolg** [sonata-nfv/tng-gtk-sp#245]
GET https://pre-int-sp-ath.5gtango.eu/api/v3/records/services
receives instance_name: null in all the elements recovered. The same happens when fetching a single element through its UUID.

**Comment by jbonnet** [comment]
Closed via #246

**Comment by felipevicens** [comment]
seems name still empty.

enriched='{:blacklist=>"[]", :callback=>"", :created_at=>2019-05-22 07:07:20 UTC, :vim_list=>[], :customer_email=>"", :customer_name=>"", :description=>"", :duration=>0.0, :egresses=>"[]", :error=>"", :flavor=>nil, :function_uuids=>nil, :id=>"b5f5fe92-44ad-487d-997f-33986839ba30", :ingresses=>"[]", :instance_uuid=>"31289d2c-f2b0-4555-a819-d746791b6fd4", :mapping=>[], :name=>nil, :number_of_instances=>nil, :request_type=>"TERMINATE_SERVICE", :scaling_type=>nil, :sla_id=>"", :status=>"READY", :updated_at=>2019-05-22 07:07:26 UTC, :vim_uuid=>"", :vnf_uuid=>"", :vnfd_uuid=>"", :service=>{:uuid=>"7c74aab8-cf4d-4c14-bf80-0dcb58ed8f9e", :vendor=>"eu.sonata-nfv", :name=>"mediapilot-service", :version=>"0.2"}}'

**Comment by jbonnet** [comment]
I think we've nailled....again, with PR #357. Please confirm
