### ISSUE TITLE
Include the user name in the service instantiation requests to the MANO

### ISSUE THREAD

**Issue by jbonnet** [sonata-nfv/tng-gtk-sp#264]
The authenticated user has been included in the requests to the SLA Manager, but it needs also to be included in the message to the MANO (the field is already there, but it goes empty). We'll need also to include this field in the slice instantiation request, so that the Slice Manager includes this data when requesting the instantiation of the services of a slice (**Doubt:** how will the Slice Manager work when we authenticate users? Maybe it will simply work as it is, if the user is authenticated?)

Due on **12th April, 2019**.

CC: @ekapassa, @mtouloup, @alemanyp

**Comment by alemanyp** [comment]
About this...
(Doubt: how will the Slice Manager work when we authenticate users? Maybe it will simply work as it is, if the user is authenticated?)

No idea how it will work, I guess as it worked until now... I suppose if there's a user, there's a session-manager somehwere on the SP but the slicer doesn't manage sessions (maybe portal? gtk? some other component?)

No problem on adding a field called "user" (or maybe "owner" ? )inside the slice-record.

**Comment by jbonnet** [comment]
Closed via #269 and #270
