### ISSUE TITLE
About a Network Slice with a NS having Ingresses field ...

### ISSUE THREAD

**Issue by alemanyp** [sonata-nfv/tng-gtk-sp#358]
When the GTk responses back or sends and update of a NS instantiation request, the ingresses field looks like a string instead of json.

![imagen](https://user-images.githubusercontent.com/30235199/58624940-ac2e4500-82d1-11e9-8636-e64649c9b8e3.png)

**Comment by jbonnet** [comment]
Implemented via #360 (also for `egresses` and `blacklist`)
