### ISSUE TITLE
Instantiation doens't change to error if descriptors not found

### ISSUE THREAD

**Issue by felipevicens** [sonata-nfv/tng-gtk-sp#366]
Description:
The status of the request doesn't change to Error when cannot find a descriptor.

How to reproduce it:
Trigger an instantiation with wrong service_uuid i.e: 
```
tng-cli service --instantiate 7ed92a4a-923f-4391-b8d9-c3f89c763692
```

Logs:
http://logs.sonata-nfv.eu/messages/graylog_52/b360e0e1-8915-11e9-8b14-0242ac130004
Function {:vnf_id=>"vnf-ma", :vnf_vendor=>"eu.5gtango", :vnf_name=>"vnf-ma", :vnf_version=>"0.5"} not found

http://logs.sonata-nfv.eu/messages/graylog_52/b360e0e4-8915-11e9-8b14-0242ac130004
Error saving request: did not get any record

**Comment by jbonnet** [comment]
Irrelevant, when using the Portal...
