### ISSUE TITLE
WIMs endpoint for NetworkSlice Multi-VIM deployment

### ISSUE THREAD

**Issue by alemanyp** [sonata-nfv/tng-gtk-sp#382]
**ISSUE DESCRIPTION**
Network Slice Mngr needs an endpoint where to send the requests to:
- get WIMs information                               ---> IA subscription topic: infrastructure.management.wan.list
- create/configure a WIM connection         ---> IA subscription topic: infrastructure.service.wan.configure
- remove/deconfigure a WIM connection   ---> IA subscription topic: infrastructure.service.wan.deconfigure

**INFORMATION NOTE:**
1. The three NEW endpoints should be similar to what it has been done for the VIMs endpoints for the Network Slice:
      GET .../slices/vims              --> to get the VIMs list (IA subscription topic: infrastructure.management.compute.list)
      POST .../slices/networks    --> to create a network within a VIM (IA subscription topic: infrastructure.service.network.create)
      DELETE .../slices/networks --> to remove a network within a VIM (IA subscription topic: infrastructure.service.network.delete)
2. This issue might have some influence to the following other issue: https://github.com/sonata-nfv/tng-gtk-sp/issues/56

**Comment by alemanyp** [comment]
@carlos-f-parada or @carlos-martins-marques, could you validate that the three previous topics are right?

**Comment by carlos-f-parada** [comment]
@alemanyp if you need to deal with WIMs (in addition to VIM) this needs to be developed by the GTK (@jbonnet), as there is only the RabbitMQ interface available

**Comment by jbonnet** [comment]
Check [here](https://github.com/sonata-nfv/tng-sp-ia/wiki/RabbitMQ-API-Reference#configure-wan-for-service-instance) and [here](https://github.com/sonata-nfv/tng-sp-ia/wiki/RabbitMQ-API-Reference#deconfigure-wan-for-service-instance)

**Comment by jbonnet** [comment]
Closed via #389, #390, #391 and #391

**Comment by alemanyp** [comment]
This issue is not done. Is what we are dealing right now.
