### ISSUE TITLE
Slicing times are not stored

### ISSUE THREAD

**Issue by felipevicens** [sonata-nfv/tng-gtk-sp#414]
We need to store the time spent by slice request (Instantiation/termination) in the same way we do it for Network services.

**Comment by jbonnet** [comment]
@felipevicens I don't think we need to store the request's `duration`: it can be calculated by `updated_at`- `created_at`. Then you can combine this with a condition: `status` equal do `READY` or `ERROR`, `request_type` equal to `CREATE_` or `TERMINATE_` `SERVICE` or `SLICE`, `SCALE_OUT` or `_IN` or `MIGRATE_FUNCTION`.

**Comment by felipevicens** [comment]
Hello @anapolg, Is it possible to calculate the difference between created_at and updated_at in the portal to get the duration value? By that way, we ensure that it will work for any type of request.

**Comment by anapolg** [comment]
Yes, it is possible. Please create an issue in the Portal for this specifying in which places this must be done. Thanks
