### ISSUE TITLE
Add a service scaling request

### ISSUE THREAD

**Issue by jbonnet** [sonata-nfv/tng-gtk-sp#94]
The payload of the scaling message would be something like this:

Initial request:

    topic: service.instance.scale

```
    scaling_type: `addvnf`
    service_instance_id: <uuid of the service instance that needs to be scaled>
    vnfd_id: <uuid of the vnfd of the vnf that needs to be added>
    constraints: (this one is optional)
        vim_id: <uuid of the VIM the new VNF should be deployed on>
```

```
    scaling_type: `removevnf`
    service_instance_id: <uuid of the service instance that needs to be scaled>
    vnf_id: <uuid of the vnf that should be removed>
```
Immediate reaction from MANO:

    topic: service.instance.scale (message will have the same correlation_id as your initial request as property)

```
    scaling_type: `addvnf` | `removevnf`
    status: SCALING
    error: null
```
Final reaction from MANO:

    topic: service.instance.scale (message will have the same correlation_id as your initial request as property)

```
    scaling_type: `addvnf` | `removevnf`
    status: `READY` | `ERROR`
    error: null | <string indicating error>
    duration: <float indicating how long the scaling took>
    nsr: <nsr, just like in instantiation message>
    vnfrs: <list of vnfrs, just like in instantiation message>
```

**Comment by jbonnet** [comment]
Hey, @tsoenen, @felipevicens we had this pretty much designed for a long time... :-)

**Comment by tsoenen** [comment]
```
    scaling_type: `addvnf`
    service_instance_id: <uuid of the service instance that needs to be scaled>
    vnfd_id: <uuid of the vnfd of the vnf that needs to be added>
    number_of_instances: <integer indication how many instances of this VNF should be added>
    constraints: (this one is optional)
        vim_id: <uuid of the VIM the new VNF should be deployed on>
```

**Comment by tsoenen** [comment]
```
    scaling_type: `REMOVE_VNF`
    service_instance_uuid: <uuid of the service instance that needs to be scaled>
    vnf_uuid: <uuid of the vnf that should be removed>
```

**Comment by jbonnet** [comment]
Still missing integration tests, but provided throug PR #261

**Comment by tsoenen** [comment]
> ```
>     scaling_type: `REMOVE_VNF`
>     service_instance_uuid: <uuid of the service instance that needs to be scaled>
>     vnf_uuid: <uuid of the vnf that should be removed>
> ```

I have extended the scale in, so that it now can be requested to scale in multiple vnfs at the same time. In that case, I need the number of instances you want to scale in, and the associated vnfd. 

```
     scaling_type: `REMOVE_VNF`
     service_instance_uuid: <uuid of the service instance that needs to be scaled>
     vnf**d**_uuid: <uuid of the vnf that should be removed>
    number_of_instances: <integer>
```

So, to scale in, two different payloads are accepted. One with `vnf_uuid` or one with `vnfd_uuid` and `number_of_instances`.

**Comment by jbonnet** [comment]
@tsoenen added the `vnf_uuid` parameter and reviewed the scaling out-only verifications, to accept scaling in, via PR #307 . Please check if this fits the needs
